### ISSUE TITLE
Tabs are not hidden

### ISSUE THREAD

**Issue by lucabrunox** [tommyvdv/tab-toggler#1]
Tabs are hidden only temporarily. When switching, creating or closing tabs ecc., the tab bar will show up  again.

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by tommyvdv** [comment]
That is to be expected from a tool that only adds/removes a class to an HTML element.
I've swapped that logic by toggling the package. Something i wanted to do all along but couldn't find due to inexperience with ATOM 😄.

**Comment by lucabrunox** [comment]
Seems to work fine, thanks :)
